function getBanatConversationReply(body, threadID = "") {
  // Una: subukan ang specific trigger groups
  const direct = getTriggerReply(body, threadID);

  if (direct) return direct;

  // ALA / ANY-MESSAGE FALLBACK
  // Kahit anong message, may random HEV-style reply.
  const alaReplies = [
    "ano na naman yan?",
    "eto na naman",
    "sige lang, dagdagan mo pa",
    "may point ba yan?",
    "walang bago",
    "same energy",
    "same script",
    "paulit-ulit ka",
    "ano ambag mo?",
    "irrelevant",
    "next",
    "skip",
    "pass muna",
    "move on tayo",
    "wrong lobby",
    "wrong server",
    "wrong target",
    "wrong answer",
    "try again",
    "again?",
    "yun na yun?",
    "tapos?",
    "may kasunod pa?",
    "bitin ah",
    "kulang sa substance",
    "low effort",
    "very low effort",
    "mid na nga, pilit pa",
    "background noise",
    "static lang",
    "signal lost",
    "connection lost",
    "brain disconnected",
    "reconnect ka muna",
    "restart ka muna",
    "reload mo yan",
    "refresh muna utak",
    "patch update kailangan mo",
    "beta build ka pa",
    "unstable release",
    "bugged character",
    "NPC dialogue",
    "same dialogue detected",
    "side quest na naman",
    "main quest muna",
    "quest failed",
    "mission failed",
    "objective not found",
    "target missing",
    "aim mo muna sarili mo",
    "friendly fire",
    "self damage",
    "critical miss",
    "missed again",
    "zero damage",
    "no impact",
    "walang effect",
    "walang dating",
    "walang laman",
    "puro salita",
    "typing lang ambag",
    "keyboard warrior",
    "chat warrior",
    "GC warrior",
    "caps lock warrior",
    "all talk",
    "talk more, say less",
    "source?",
    "resibo?",
    "proof?",
    "evidence?",
    "galing saan yan?",
    "headcanon mo lang yan",
    "imbento build",
    "delusion build",
    "reality check",
    "logic check",
    "common sense check",
    "bagsak lahat",
    "review ka muna",
    "aral ka muna",
    "isip muna bago send",
    "delete mo yan",
    "unsend mo habang may oras",
    "second take",
    "retake ka muna",
    "cut, ulitin natin",
    "bad take",
    "weak take",
    "weak entry",
    "weak opening",
    "pang-intro lang",
    "intro pa lang sablay na",
    "HEV mode pero walang presence",
    "underground pero maingay",
    "lowkey daw",
    "lowkey pero puro chat",
    "cold daw",
    "cold pero walang impact",
    "dark mode personality",
    "black screen utak",
    "empty lobby",
    "empty server",
    "spawn point ka lang",
    "respawn ka muna",
    "balik lobby",
    "logout ka muna",
    "mute mo sarili mo",
    "quiet mode muna",
    "pause ka muna",
    "calm down sa keyboard",
    "pikon detected",
    "triggered detected",
    "short fuse",
    "konting banat, sabog",
    "fragile build",
    "low durability",
    "glass build",
    "budget villain",
    "tutorial villain",
    "mini boss behavior",
    "final boss daw",
    "final boss sa imagination",
    "king daw",
    "nasaan kaharian?",
    "crown muna bago yabang",
    "trono gawa sa karton",
    "royalty sa bio",
    "ordinaryo sa chat",
    "gangster sa profile",
    "keyboard warrior sa actual",
    "presence check failed",
    "aura check failed",
    "vibe check failed",
    "skill check failed",
    "logic check failed",
    "HEV check failed",
    "system error",
    "fatal error",
    "critical error",
    "404 sense not found",
    "logic.exe not responding",
    "common sense.exe missing",
    "personality.exe stopped",
    "confidence.exe running",
    "storage full ng nonsense",
    "RAM puro yabang",
    "CPU pagod na",
    "processor surrendered",
    "low spec behavior",
    "factory reset kailangan",
    "clear cache ka muna",
    "reinstall common sense",
    "hard reset",
    "system crash",
    "reconnect to reality",
    "reality server unavailable",
    "server down yata",
    "maintenance ka muna",
    "offline ka muna",
    "wala ka sa server",
    "wrong timeline",
    "wrong dimension",
    "wrong universe",
    "NPC ka lang dito",
    "background character",
    "side character behavior",
    "extra ka sa eksena",
    "walang character development",
    "season 1 behavior",
    "episode filler",
    "filler episode ka",
    "skip episode",
    "deleted scene",
    "unused dialogue",
    "scrapped content",
    "cut content",
    "unnecessary update",
    "bug report kita",
    "reportable behavior",
    "case closed",
    "wala nang kailangan sabihin",
    "next topic",
    "next victim",
    "next message",
    "continue mo lang, nakakatawa",
    "sige pa",
    "dagdagan mo pa",
    "wag ka titigil",
    "ituloy mo yan",
    "sayang effort mo",
    "effort detected",
    "effort walang result",
    "ang haba, walang point",
    "maikli, wala ring point",
    "point missing",
    "context missing",
    "common sense missing",
    "brain cells missing",
    "skill missing",
    "presence missing",
    "aura missing",
    "content missing"
  ];

  const reply = pickBanatReply(threadID, alaReplies);

  if (reply) {
    rememberBanatReply(threadID, reply);
  }

  return reply;
    }
